PhoneComp/Controllers/SContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.OleDb;
using System.Transactions;
using PhoneComp.Models;
using PhoneComp.DAL;
using PhoneComp.Lib;
using PagedList;

namespace PhoneComp.Controllers
{
    public class SContactController : BaseController
    {
        private PhoneCompContext db = new PhoneCompContext();

        //
        // GET: /SContact/

        public ActionResult Index(Contact entity, int? pageIndex, int? pageSize)
        {            
            var numbers =
                from num in db.Contacts
                where (num.IsDeleted == false )
                select num;
            if (!string.IsNullOrEmpty(entity.LinkerMobile))
            {
                numbers = numbers.Where(n => n.LinkerMobile.ToUpper().Contains(entity.LinkerMobile.ToUpper()));
            }
            if (!string.IsNullOrEmpty(entity.LinkerName))
            {
                numbers = numbers.Where(n => n.LinkerName.ToUpper().Contains(entity.LinkerName.ToUpper()));
            }
            var contacts = numbers.OrderByDescending(n=>n.ContactID).ToPagedList(pageIndex ?? 1, pageSize ?? 10);
            
           // var contacts = db.Contacts.Include(c => c.Suspects);
            return View(contacts);
        }
       

        /// <summary>
        /// 新增或编辑
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult CreateEdit(int? id)
        {
            var suspects = db.Suspectses.Where(s => s.IsDeleted == false);
            ViewBag.SuspectID = new SelectList(suspects, "SuspectID", "SuspectMobile");
            Contact contact = new Contact();
            if (id.GetValueOrDefault() != 0)
            {
                contact = db.Contacts.Find(id);
               
                if (contact == null || contact.IsDeleted == true)
                {
                    contact = new Contact();
                }
            }
            //create
            return View(contact);
        }

        [HttpPost]
        public ActionResult CreateEdit(Contact contact)
        {
            try
            {
                string result = string.Empty;
                if (contact.SuspectID <= 0)
                {
                    result = "0|请先选择所属嫌疑人！";
                    return Content(result);
                }
                if (string.IsNullOrEmpty(contact.LinkerName))
                {
                    result = "0|联系人不能为空！";
                    return Content(result);
                }
                if (string.IsNullOrEmpty(contact.LinkerMobile))
                {
                    result = "0|联系人手机不能为空！";
                    return Content(result);
                }

                if (contact.ContactID > 0)
                {                    
                    db.Entry(contact).State = EntityState.Modified;
                    contact.IsDeleted = false;
                    contact.LastUpdateDate = DateTime.Now;
                    contact.LastUpdateUserID = CurrentUser.UID;
                    result = db.SaveChanges() == 1 ? "1|操作成功|/Scontact/Index" : "0|操作失败";
                    return Content(result);
                }
                else
                {
                    contact.IsDeleted = false;
                    contact.CreateDate = DateTime.Now;
                    contact.CreateUserID = CurrentUser.UID;
                    db.Contacts.Add(contact);
                    result = db.SaveChanges() == 1 ? "1|操作成功|/Scontact/Index" : "0|操作失败";
                    return Content(result);
                }
            }
            catch (Exception ex)
            {
                return Content("0|" + ex.Message.ToString());
            }
        }

        //
        // POST: /SContact/Delete/5
        /// <summary>
        /// 删除联系人
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                string result = string.Empty;
                Contact contact = db.Contacts.Find(id);
                contact.IsDeleted = true;
                db.Entry(contact).State = EntityState.Modified;
                result = db.SaveChanges() == 1 ? "1|操作成功" : "0|操作失败";
                return Content(result);
            }
            catch (Exception ex)
            {
                return Content("0|" + ex.Message.ToString());
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        #region 批量导入通讯录
        /// <summary>
        /// 批量导入嫌疑人通讯录
        /// </summary>
        /// <returns></returns>
        public ActionResult BatchImport()
        {
            var suspects = db.Suspectses.Where(s => s.IsDeleted == false);
            ViewBag.SuspectID = new SelectList(suspects, "SuspectID", "SuspectMobile");
            return View();
        }
        [HttpPost]
        public ActionResult ContactImport(Contact contact)
        {
            try
            {
                string result = string.Empty;
                int totalCount = 0; // 待导入总条数  
                int successCount = 0;
                string FileName;
                string savePath;
                string fileEx;

                HttpPostedFileBase file = Request.Files["files"];
                if (contact.SuspectID <= 0)
                {
                    result = "请先选择所属嫌疑人！";
                    return Content("0|" + result);
                }

                if (file == null || file.ContentLength <= 0)
                {
                    result = "文件不能为空！";
                    return Content("0|" + result);
                }
                else
                {
                    string filename = Path.GetFileName(file.FileName);
                    int filesize = file.ContentLength;
                    fileEx = Path.GetExtension(filename);
                    string NoFileName = Path.GetFileNameWithoutExtension(filename);
                    int Maxsize = 4000 * 1024;
                    string FileType = ".xls,.xlsx";

                    FileName = NoFileName + DateTime.Now.ToString("yyyyMMddhhmmss") + fileEx;
                    if (!FileType.Contains(fileEx))
                    {
                        result = "文件类型不对，只能导入xls和xlsx格式的文件";
                        return Content("0|" + result);
                    }
                    if (filesize >= Maxsize)
                    {
                        result = "上传文件超过8M，不能上传";
                        return Content("0|" + result);
                    }
                    string path = AppDomain.CurrentDomain.BaseDirectory + "uploads/excel/";

                    savePath = Path.Combine(path, FileName);
                    file.SaveAs(savePath);
                }

                string strConn = string.Empty;
                if (fileEx.Equals(".xlsx"))
                {
                    strConn = "Provider=Microsoft.Ace.OleDb.12.0;Data Source=" + savePath + ";Extended Properties='Excel 12.0 Xml; HDR=YES; IMEX=1'";
                }
                else if (fileEx.Equals(".xls"))
                {
                    strConn = "Provider=Microsoft.Jet.OleDb.4.0;" + "data source=" + savePath + ";Extended Properties='Excel 8.0; HDR=YES; IMEX=1'";
                }
                OleDbConnection conn = new OleDbConnection(strConn);
                conn.Open();
                OleDbDataAdapter myCommand = new OleDbDataAdapter("SELECT * FROM [Sheet1$]", strConn);
                DataSet myDataSet = new DataSet();
                try
                {
                    myCommand.Fill(myDataSet, "ContactInfo");
                }
                catch (Exception ex)
                {
                    result = ex.Message;
                    return Content("0|" + result);
                }
                DataTable table = myDataSet.Tables["ContactInfo"].DefaultView.ToTable();

                using (TransactionScope transaction = new TransactionScope())
                {
                    int suspectID = contact.SuspectID;
                    DataRow dr = null;
                    for (int i = 0; i < table.Rows.Count; i++)
                    {
                        totalCount++;
                        dr = table.Rows[i];
                        if (insertContactSQL(dr, "Contact", suspectID) == 1)
                        {
                            successCount++;
                        }
                    }
                    transaction.Complete();
                }
                if (totalCount > 0)
                {
                    if (successCount > 0)
                    {
                        result = "1|成功导入" + successCount + "条记录。|/SContact/index";
                    }
                    else
                    {
                        result = "0|导入失败";
                    }
                }
                else
                {
                    result = "0|没有要导入的数据或数据已存在。";
                }
                return Content(result);
            }
            catch (Exception ex)
            {
                return Content("0|" + ex.Message.ToString());
            }
        }


        private int insertContactSQL(DataRow dr, string tableName, int suspectID)
        {
            //excel表中的列名和数据库中的列名一定要对应  
            int flag = 0;
            int queryCount = 0;
            var linkerName = dr["联系人姓名"].ToString();
            var linkerMobile = dr["联系人号码"].ToString();
            if (!string.IsNullOrEmpty(linkerName) && !string.IsNullOrEmpty(linkerMobile))
            {
                string querySql = "SELECT COUNT(*) FROM " + tableName

PhoneComp/Views/SContact/BatchImport.cshtml
@model PhoneComp.Models.Contact
@{
    ViewBag.Title = "批量导入手机联系人";
    Layout = "~/Views/Shared/_LayoutCustom.cshtml"; 
}

<ol class="breadcrumb">
    <li><a href="/Home/Index">Home</a></li>
    <li><a href="/Scontact/Index">嫌疑人通讯录</a></li>
    <li class="avtive">批量上传</li>
</ol>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>嫌疑人通讯录导入</h2>
    </div>
    <div class="panel-body">
        
        <form name="importform" id="importform" action="" method="post" enctype="multipart/form-data">
            <div style="margin-top: 20px;">
                <fieldset id="myfieldset1">
                    <legend>嫌疑人通讯录导入</legend>
                    <div class="alert alert-danger hidden" id="Tips">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <strong>Error!</strong><span id="TipsMsg"></span>
                    </div>
                    <div class="form-group ">
                        <label>选择所属嫌疑人：</label>
                        @Html.DropDownList("SuspectID", (SelectList)ViewBag.SuspectID, new { @class = "chosen-select", style = "width:140px" })
                        @Html.ValidationMessageFor(model => model.SuspectID)
                    </div>
                    <div class="form-group">
                        <label>选择嫌疑人通讯录文件：</label>
                        <input id="FileUpload" type="file" name="files" class="btn btn-info validate[required]" />
                    </div>
                    <div class="form-group ">
                        <input type="button" id="btnImport" class="btn btn-success btn-lg active" value="确认导入" />
                    </div>
                    <p style="color: Red; text-align: center;"></p>
                </fieldset>
            </div>
        </form>
        <div>
            <fieldset id="myfieldset">
                <legend>excel模版格式 </legend>
                <div class="alert alert-info">按规定的模板制作您的excel表格</div>
                <div class="row">
                    <div class="col-xs-6 ">
                        <a href="#" class="thumbnail">
                            <img data-src="holder.js/100%x180" src="/Images/SuspectsContact.png" alt="联系人模板样式" style="margin-left:10px;">
                        </a>
                    </div>
                </div>
                <a href="/Download/importContact.xls" class="btn btn-primary btn-lg active" role="button">下载模板</a>
            </fieldset>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#btnImport").click(function () {
            var file = $("#FileUpload").val();
            if (file == undefined || file == "") {
                $("#TipsMsg").html("请先选择上传的文件!");
                $("#Tips").removeClass("hidden");
            } else {
                $("#TipsMsg").html("");
                $("#Tips").addClass("hidden");
                var formData = new FormData(document.getElementById("importform"));
                messageBox("正在提交，请稍候……");
                $.ajax({
                    url: '/SContact/ContactImport',
                    type: 'POST',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        formResult(data)
                    }
                })
            }
        });
    });
</script>

PhoneComp/Views/SContact/ContactComp.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList<PhoneComp.Models.UsedWorker>

@{
    ViewBag.Title = "嫌疑人通讯录比对";
    Layout = "~/Views/Shared/_LayoutCustom.cshtml";
}

<ol class="breadcrumb">
    <li><a href="/Home/Index">Home</a></li>
    <li><a href="/Scontact/Index">嫌疑人通讯录</a></li>
    <li class="avtive">嫌疑人通讯录比对</li>
</ol>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>嫌疑人通讯录比对</h2>
    </div>
    <div class="panel-body">
        @if (ViewBag.error != null)
        {
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Error!</strong> @ViewBag.error
            </div>
        }

        @Html.DropDownList("SuspectID", (SelectList)ViewBag.SuspectID, new { @class = "chosen-select-deselect", style = "width:140px" })
        <button class="btn btn-primary" name="contactComp" onclick="CompSubmit('/SContact/ContactComp','SuspectID')">开始比对</button>
    </div>
    <div id="tableList" class="panel-body">

        <table class="table">
            <tr>
                <th>姓名 </th>
                <th>身份证号</th>
                <th>职业</th>
                <th>工作地址</th>
                <th>家庭地址</th>
                <th>联系方式1</th>
                <th>联系方式2</th>
                <th>联系方式3</th>
            </tr>
            @if (Model != null)
            {
                foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IDcard)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Job)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JobAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HomeAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Phone1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Phone2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Phone3)
                    </td>
                </tr>
                }
            }
        </table>
        @if (Model != null)
        {
            <div class="">
                共 @(Model.TotalItemCount) 条记录

    @Html.PagedListPager(Model, pageIndex => Url.Action("Index", new { pageIndex, pageSize = Request["pageSize"] }))
            </div>
        }

    </div>
</div>
<script>
    function CompSubmit(url, id) {
        var param = $("#" + id).val();
        if (param > 0) {
            window.location.href = url + "?SuspectID=" + param;
        }
    }
</script>

PhoneComp/Views/SContact/Create.cshtml
@model PhoneComp.Models.Contact

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Contact</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SuspectID, "Suspects")
        </div>
        <div class="editor-field">
            @Html.DropDownList("SuspectID", String.Empty)
            @Html.ValidationMessageFor(model => model.SuspectID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LinkerName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LinkerName)
            @Html.ValidationMessageFor(model => model.LinkerName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LinkerMobile)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LinkerMobile)
            @Html.ValidationMessageFor(model => model.LinkerMobile)
            <span style="color:#f00">@ViewBag.errorMsg</span>
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhoneComp/Views/SContact/CreateEdit.cshtml
@model PhoneComp.Models.Contact


@{
    ViewBag.Title = "新增|编辑 通讯录联系人";
    Layout = "~/Views/Shared/_LayoutCustom.cshtml";
}

<ol class="breadcrumb">
    <li><a href="/Home/Index">Home</a></li>
    <li><a href="/Scontact/Index">嫌疑人通讯录</a></li>
    <li class="avtive">新增|编辑</li>
</ol>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>新增|编辑 通讯录联系人</h2>
    </div>
    <div class="panel-body">
        @if (ViewBag.errorMsg != null)
        {
            <div class="alert alert-danger">@ViewBag.errorMsg</div>
        }

        <form class="form-horizontal" id="contactform" name="contactform" action="/Scontact/CreateEdit" method="post" role="form">
            <div class="form-group">
                <label class="col-sm-2 control-label" for="SuspectName">嫌疑人号码</label>
                <div class="col-sm-8">                    
                    @Html.DropDownList("SuspectID", (SelectList)ViewBag.SuspectID, new { @class = "chosen-select", style = "width:140px" })
                    <a href="/Suspect/CreateEdit"> 新增嫌疑人</a>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="LinkerName">联系人</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control validate[required]" id="LinkerName" name="LinkerName" value="@Model.LinkerName" placeholder="联系人">
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label" for="LinkerMobile">联系人手机</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control validate[required,custom[phone]]" id="LinkerMobile" name="LinkerMobile" value="@Model.LinkerMobile" placeholder="联系人手机">
                </div>
            </div>
            <input type="hidden" name="CreateDate" value="@Model.CreateDate" />
            <input type="hidden" name="CreateUserID" value="@Model.CreateUserID" />
            <input type="hidden" name="ContactID" value="@Model.ContactID" />
            <div>
                <div class="center-block col-sm-6" style="float: none;">
                    <input type="button" id="submit" class="btn btn-primary" value="新增|编辑" />
                    @Html.ActionLink("取消","Index",null,new{@class="btn btn-default"})
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#submit").click(function () {
            submitForm("contactform", "/Scontact/CreateEdit", $("#contactform").serialize());
        });

        myFormValidation("contactform");
    });
</script>

PhoneComp/Views/SContact/Delete.cshtml
@model PhoneComp.Models.Contact

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Contact</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Suspects.SuspectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Suspects.SuspectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LinkerName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LinkerName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LinkerMobile)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LinkerMobile)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsDeleted)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsDeleted)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

PhoneComp/Views/SContact/Details.cshtml
@model PhoneComp.Models.Contact

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Contact</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Suspects.SuspectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Suspects.SuspectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LinkerName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LinkerName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LinkerMobile)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LinkerMobile)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsDeleted)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsDeleted)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ContactID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PhoneComp/Views/SContact/Edit.cshtml
@model PhoneComp.Models.Contact

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Contact</legend>

        @Html.HiddenFor(model => model.ContactID)

        <div class="editor-label">
            @Html.LabelFor(model => model.SuspectID, "Suspects")
        </div>
        <div class="editor-field">
            @Html.DropDownList("SuspectID", String.Empty)
            @Html.ValidationMessageFor(model => model.SuspectID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LinkerName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LinkerName)
            @Html.ValidationMessageFor(model => model.LinkerName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LinkerMobile)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LinkerMobile)
            @Html.ValidationMessageFor(model => model.LinkerMobile)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsDeleted)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsDeleted)
            @Html.ValidationMessageFor(model => model.IsDeleted)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhoneComp/Views/SContact/Index.cshtml
@using PagedList.Mvc;
@using PhoneComp.Models;
@model PagedList.PagedList<Contact>

@{
    ViewBag.Title = "嫌疑人通讯录";
    Layout ="~/Views/Shared/_LayoutCustom.cshtml";
}

<ol class="breadcrumb">
    <li><a href="/Home/Index">Home</a></li>
    <li class="avtive">嫌疑人通讯录</li>
</ol>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2>嫌疑人通讯录</h2>
    </div>
    <div class="panel-body">
        <div id="Tips" class="alert alert-danger alert-dismissable hidden">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <span></span>
        </div>
        <div class="pull-left">
            @Html.ActionLink("新增", "CreateEdit", null, new { @class="btn btn-success"})
            @Html.ActionLink("批量导入", "BatchImport", null, new { @class="btn btn-success"})
            @Html.ActionLink("比对数据库","ContactComp","SContact",null,new{@class="btn btn-info"})             
        </div>
        <div class="pull-right">
            <form class="form-inline" role="form">
                <div class="form-group">
                    <label class="sr-only" for="LinkerName">联系人</label>
                    <input class="form-control" type="text" name="LinkerName" value="@Request.QueryString["LinkerName"]" placeholder="联系人" />
                </div>
                <div class="form-group">
                    <label class="sr-only" for="LinkerMobile">联系电话</label>
                    <input class="form-control" type="text" name="LinkerMobile" value="@Request.QueryString["LinkerMobile"]" placeholder="联系电话" />
                </div>
                <button type="submit" class="btn btn-primary">搜索</button>
            </form>
        </div>
    </div>
    
    <table class="table">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" value="" onclick=""></th>                
                <th>联系人</th>
                <th>联系电话</th>
                <th>嫌疑人名称 </th>
                <th>嫌疑人手机号</th>
                <th>录入人</th>
                <th>录入时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" value="@item.ContactID" name="ContactID"></td>                    
                    <td>
                        @Html.DisplayFor(modelItem => item.LinkerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LinkerMobile)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Suspects.SuspectName)
                    </td>
                    <td>@item.Suspects.SuspectMobile</td>
                    <td>@((item.Member?? new PhoneComp.Models.Member()).RealName)</td> 
                    <td>@(item.CreateDate== null ?"":item.CreateDate.GetValueOrDefault().ToString("yyyy-MM-dd"))</td>
                    <td>
                        <ul class="list-inline">
                            <li>@Html.ActionLink("Edit", "CreateEdit", new { id = item.SuspectID })</li>
                            <li><a href="javascript:void(0);" onclick="ajaxPostDel('/Scontact/Delete',@(item.ContactID))">Delete</a></li>
                        </ul>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
@*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@
<div class="">    
共 @(Model.TotalItemCount) 条记录

@Html.PagedListPager(Model, pageIndex => Url.Action("Index", new { pageIndex, pageSize = Request["pageSize"]}))
    </div>